### ISSUE TITLE
EM-AY-DEVS-1 List of food places in script do not have consistent capitalization

### ISSUE THREAD

**Issue by mdang8** [em-ay-devs/food#1]
All of the available food places should be written with their official names.

**Comment by pvargas** [comment]
They don't have to, since the script capitalizes them regardless.

**Comment by mdang8** [comment]
I don't believe this issue has been resolved. What if one of the food places is [Café du Pays](http://cafedupays.com/)? The `title()` method on [Line 41](https://github.com/em-ay-devs/food/blob/75f6cf59ccf80f00830622fd6c357d190e59e767/recommend.py#L41) will format it to "Cafe *Du* Pays" which is not the correct capitalization of the name.

**Comment by pvargas** [comment]
The problem with this is that we would have to sanitize all the list items by hand, since different stylizations won't necessarily "correct" title format. e.g. _Café du Pays_ is actually stylized as  [_CAFÉ DU PAYS_](http://cafedupays.com/)
