### ISSUE TITLE
Add better selection logic

### ISSUE THREAD

**Issue by aperullo** [em-ay-devs/food#9]
Current logic uses too many calls to an external library, and also requires a loop. 
A more pythonic approach would be to shuffle the list and then simply use a list slice to select the first N elements.

**Comment by pvargas** [comment]
Please explain what is wrong with the current selection logic.

**Comment by pvargas** [comment]
> Current logic uses too many calls to an external library, and also requires a loop.
> A more pythonic approach would be to shuffle the list and then simply use a list slice to select the first N elements.

This is fine. For future reference: modules from the Python Standard Library are not considered "external libraries".
